### ISSUE TITLE
How do I try this out?

### ISSUE THREAD

**Issue by tsiq-swyx** [wiredjs/wired-button#6]
Tried `bower install` but it doesnt work.. would appreciate some basic guide somewhere in a readme?

**Comment by pshihn** [comment]
Yes. Sorry, I havent added documentation here. All of these are posted on Webcomponents.org
https://www.webcomponents.org/introduction should get you started.

**Comment by pshihn** [comment]
Also, look at: https://www.webcomponents.org/element/wiredjs/wired-button

**Comment by hansonfang** [comment]
Why do I always get an error message in Chrome console:
```
Uncaught TypeError: Failed to resolve module specifier ···Relative references must start with either "/", "./", or "../".
```
How do I place the HTML file location to import the right path?

**Comment by pshihn** [comment]
@hansonfang the comments above are bit outdated. Let me  write something up better.

**Comment by pshihn** [comment]
Related: https://github.com/wiredjs/wired-elements/issues/8

**Comment by pshihn** [comment]
Added playgrounds on readme and the main website:

[Wired Elements playground](https://stackblitz.com/edit/wired-elements?file=index.html)

[Wired Elements in React playground](https://stackblitz.com/edit/wired-elements-react?file=index.js)
